import { Moment } from 'moment';

export const enum TipoAdjunto {
    NOTIFICACION_DE_ASIGNACION_FISCAL = 'NOTIFICACION_DE_ASIGNACION_FISCAL',
    NOTIFICACION_DE_INHABILITA = 'NOTIFICACION_DE_INHABILITA',
    NOTIFICACION_DE_ACEPTACION = 'NOTIFICACION_DE_ACEPTACION',
    DESIGNA_NUEVO_FISCAL = 'DESIGNA_NUEVO_FISCAL',
    RESOLUCION_DE_INVESTIGACION = 'RESOLUCION_DE_INVESTIGACION',
    INFORME_DE_ELEVAR_SUMARIO = 'INFORME_DE_ELEVAR_SUMARIO',
    INFORME_DE_PROPONER_SOBRE_SEIMIENTO = 'INFORME_DE_PROPONER_SOBRE_SEIMIENTO',
    INFORME_DE_FORMULACION_DE_CARGOS = 'INFORME_DE_FORMULACION_DE_CARGOS',
    RESOLUCION_DE_ELEVA_SUMARIO = 'RESOLUCION_DE_ELEVA_SUMARIO',
    NOTIFICACION_DE_RECHAZO_ELEVA_SUMARIO = 'NOTIFICACION_DE_RECHAZO_ELEVA_SUMARIO',
    RESOLUCION_DE_PROPONER_SOBRE_SEIMIENTO = 'RESOLUCION_DE_PROPONER_SOBRE_SEIMIENTO',
    NOTIFICACION_DE_FORMULACION_DE_CARGOS = 'NOTIFICACION_DE_FORMULACION_DE_CARGOS',
    INFORME_DESCARGO = 'INFORME_DESCARGO',
    INFORME_DE_SOLICITUD_DE_TERMINO_APROBATORIO = 'INFORME_DE_SOLICITUD_DE_TERMINO_APROBATORIO',
    INFORME_DE_TERMINO_APROBATORIO = 'INFORME_DE_TERMINO_APROBATORIO',
    INFORME_DE_PROPUESTA_DE_SANCION = 'INFORME_DE_PROPUESTA_DE_SANCION',
    RESOLUCION_DE_SANCION = 'RESOLUCION_DE_SANCION',
    RESOLUCION_DE_RECHAZO_DE_SANCION = 'RESOLUCION_DE_RECHAZO_DE_SANCION',
    NOTIFICACION_DE_RECHAZO_PROPONE_SOBRE_SEIMEINTO = 'NOTIFICACION_DE_RECHAZO_PROPONE_SOBRE_SEIMEINTO',
    INFORME_DE_REALIZAR_DILIGENCIAS = 'INFORME_DE_REALIZAR_DILIGENCIAS',
    INFORME_DE_PROPONER_MEDIDAS = 'INFORME_DE_PROPONER_MEDIDAS',
    RESOLUCION_DE_ACEPTACION_DE_LAS_MEDIDAS = 'RESOLUCION_DE_ACEPTACION_DE_LAS_MEDIDAS',
    RESOLUCION_DE_REAPERTURA = 'RESOLUCION_DE_REAPERTURA',
    INFORME_DE_TRAER_EL_PROCESO_AL_INICIO = 'INFORME_DE_TRAER_EL_PROCESO_AL_INICIO',
    INFORME_DE_RECURSO_DE_REPOSICION = 'INFORME_DE_RECURSO_DE_REPOSICION',
    NOTIFICACION_DE_RECURSO_DE_REPOSICION = 'NOTIFICACION_DE_RECURSO_DE_REPOSICION',
    INFORME_DE_ABSOLVER = 'INFORME_DE_ABSOLVER',
    RESOLUCION_DE_ACEPTACION_DE_RESOLUCION_DE_ABSOLVER = 'RESOLUCION_DE_ACEPTACION_DE_RESOLUCION_DE_ABSOLVER',
    NOTIFICACION_DE_REGISTRO_DE_RESOLUCION_DE_ABSOLVER = 'NOTIFICACION_DE_REGISTRO_DE_RESOLUCION_DE_ABSOLVER',
    NOTIFICACION_DE_APLICAR_MEDIDAS_DISCIPLINARIAS = 'NOTIFICACION_DE_APLICAR_MEDIDAS_DISCIPLINARIAS',
    INFORME_DE_ACEPTACION_TOTAL = 'INFORME_DE_ACEPTACION_TOTAL',
    INFORME_DE_ACEPTACION_PARCIAL = 'INFORME_DE_ACEPTACION_PARCIAL',
    INFORME_DE_RECHAZO_DE_RECURSO_DE_REPOSICION = 'INFORME_DE_RECHAZO_DE_RECURSO_DE_REPOSICION',
    RESOLUCION_AFINATORIA_CENSURA = 'RESOLUCION_AFINATORIA_CENSURA',
    RESOLUCION_AFINATORIA_MULTA = 'RESOLUCION_AFINATORIA_MULTA',
    RESOLUCION_AFINATORIA_SUSPENSION = 'RESOLUCION_AFINATORIA_SUSPENSION',
    NOTIFICACION_DE_RESOLUCION_AFINATORIA_CENSURA = 'NOTIFICACION_DE_RESOLUCION_AFINATORIA_CENSURA',
    NOTIFICACION_DE_RESOLUCION_AFINATORIA_MULTA = 'NOTIFICACION_DE_RESOLUCION_AFINATORIA_MULTA',
    NOTIFICACION_DE_RESOLUCION_AFINATORIA_SUSPENSION = 'NOTIFICACION_DE_RESOLUCION_AFINATORIA_SUSPENSION',
    RESOLUCION_AFINATORIA_DESTITUCION = 'RESOLUCION_AFINATORIA_DESTITUCION',
    NOTIFICACION_DE_RESOLUCION_AFINATORIA_DESTITUCION = 'NOTIFICACION_DE_RESOLUCION_AFINATORIA_DESTITUCION',
    RESOLUCION_AFINATORIA_DE_ABSOLUCION_TOTAL = 'RESOLUCION_AFINATORIA_DE_ABSOLUCION_TOTAL',
    RESOLUCION_AFINATORIA_DE_ABSOLUCION_PARCIAL = 'RESOLUCION_AFINATORIA_DE_ABSOLUCION_PARCIAL',
    INFORME_DE_APLICAR_MEDIDAS = 'INFORME_DE_APLICAR_MEDIDAS',
    NOTIFICACION_DE_RESOLUCION_AFINATORIA_DE_ABSOLUCION_PARCIAL = 'NOTIFICACION_DE_RESOLUCION_AFINATORIA_DE_ABSOLUCION_PARCIAL',
    NOTIFICACION_DE_RESOLUCION_AFINATORIA_DE_ABSOLUCION_TOTAL = 'NOTIFICACION_DE_RESOLUCION_AFINATORIA_DE_ABSOLUCION_TOTAL',
    INFORME_DE_RESUCURSO_DE_REPOSICION_CON_APELACION_DE_SUBSIDIO = 'INFORME_DE_RESUCURSO_DE_REPOSICION_CON_APELACION_DE_SUBSIDIO',
    INFORME_JURIDICO = 'INFORME_JURIDICO'
}

export const enum FileUploadStatus {
    ANALIZANDO = 'ANALIZANDO',
    ADJUNTO_DE_RESPUESTA_TEMPORAL = 'ADJUNTO_DE_RESPUESTA_TEMPORAL',
    INFECTADO = 'INFECTADO',
    ESCANEADO_SIN_VIRUS = 'ESCANEADO_SIN_VIRUS',
    FORMATO_Y_PESO_VALIDADO = 'FORMATO_Y_PESO_VALIDADO',
    SUCCESS = 'SUCCESS',
    ERROR = 'ERROR'
}

export interface IAdjunto {
    id?: number;
    tipoAdjunto?: TipoAdjunto;
    nombre?: string;
    descripcion?: string;
    fechaCreado?: Moment;
    fechaSubido?: Moment;
    archivoNombre?: string;
    archivoMimeType?: string;
    archivoSize?: number;
    estado?: FileUploadStatus;
    archivo?: any;
    archivoContentType?: string;
    alfrescoNodeId?: string;
    alfrescoNodePath?: string;
    localPath?: string;
    hash?: string;
    providenciaId?: number;
    movimientoProvidenciaId?: number;
    derivacion_id?: number;
    respuesta_id?: number;
}

export class Adjunto implements IAdjunto {
    constructor(
        public id?: number,
        public tipoAdjunto?: TipoAdjunto,
        public nombre?: string,
        public descripcion?: string,
        public fechaCreado?: Moment,
        public fechaSubido?: Moment,
        public archivoNombre?: string,
        public archivoMimeType?: string,
        public archivoSize?: number,
        public estado?: FileUploadStatus,
        public archivo?: any,
        public archivoContentType?: string,
        public alfrescoNodeId?: string,
        public alfrescoNodePath?: string,
        public localPath?: string,
        public hash?: string,
        public providenciaId?: number,
        public movimientoProvidenciaId?: number,
        public derivacion_id?: number,
        public respuesta_id?: number
    ) {}
}
