package com.gruposolux.rcivil.pdisciplinario.security;

import java.util.StringTokenizer;

/**
 * Constants for Spring Security authorities.
 */
public final class AuthoritiesConstants {

    public static final String ADMIN = "ROLE_ADMIN";
    public static final String USER = "ROLE_USER";
    public static final String ANONYMOUS = "ROLE_ANONYMOUS";
    public static final String CREAR_PROVIDENCIA_PRIVILEGE = "CREAR_PROVIDENCIA_PRIVILEGE";
    public static final String CREAR_PERFIL_PRIVILEGE = "CREAR_PERFIL_PRIVILEGE";
    public static final String CREAR_FICHA_INGRESO_PRIVILAGE = "CREAR_FICHA_INGRESO_PRIVILAGE";
    public static final String CREAR_GRUPO_PRIVILEGE = "CREAR_GRUPO_PRIVILEGE";
    public static final String CREAR_USUARIO_PRIVILEGE = "CREAR_USUARIO_PRIVILEGE";
    public static final String CREAR_PLANTILLA_PRIVILEGE = "CREAR_PLANTILLA_PRIVILEGE";
    public static final String EDITAR_INVESTIGACION_PRIVILEGE = "EDITAR_INVESTIGACION_PRIVILEGE";
    public static final String EDITAR_PERFIL_PRIVILEGE = "EDITAR_PERFIL_PRIVILEGE";
    public static final String EDITAR_USUARIO_PRIVILEGE = "EDITAR_USUARIO_PRIVILEGE";
    public static final String EDITAR_GRUPO_PRIVILEGE = "EDITAR_GRUPO_PRIVILEGE";
    public static final String EDITAR_PLANTILLA_PRIVILEGE = "EDITAR_PLANTILLA_PRIVILEGE";
    public static final String EDITAR_ADJUNTO_PRIVILEGE = "EDITAR_PROVIDENCIA_PRIVILEGE";
    public static final String EDITAR_PROVIDENCIA_PRIVILEGE = "ACTUALIZAR_ADJUNTO_PRIVILEGE";
    public static final String EDITAR_DOCUMENTO_PRIVILEGE = "ACTUALIZAR_DOCUMENTO_PRIVILEGE";
    public static final String ELIMINAR_DOCUMENTO_PRIVILEGE = "ELIMINAR_DOCUMENTO_PRIVILEGE";
    public static final String ELIMINAR_GRUPO_PRIVILEGE = "ELIMINAR_GRUPO_PRIVILEGE";
    public static final String ELIMINAR_PERFIL_PRIVILEGE = "ELIMINAR_PERFIL_PRIVILEGE";
    public static final String ELIMINAR_USUARIO_PRIVILEGE = "ELIMINAR_USUARIO_PRIVILEGE";
    public static final String ELIMINAR_PLANTILLA_PRIVILEGE = "ELIMINAR_PLANTILLA_PRIVILEGE";
    public static final String ELIMINAR_ADJUNTO_PRIVILEGE = "ELIMINAR_ADJUNTO_PRIVILEGE";
    public static final String VISUALIZAR_FICHA_INGRESO_PRIVILEGE = "VISUALIZAR_FICHA_INGRESO_PRIVILEGE";
    public static final String VISUALIZAR_INVESTIGACION_PRIVILEGE = "VISUALIZAR_INVESTIGACION_PRIVILEGE";
    public static final String VISUALIZAR_ADJUNTO_PRIVILEGE = "VISUALIZAR_ADJUNTO_PRIVILEGE";
    public static final String VISUALIZAR_DOCUMENTO_PRIVILEGE = "VISUALIZAR_DOCUMENTO_PRIVILEGE";
    public static final String VISUALIZAR_PROVIDENCIA_PRIVILEGE = "VISUALIZAR_PROVIDENCIA_PRIVILEGE";
    public static final String VISUALIZAR_PERFIL_PRIVILEGE = "VISUALIZAR_PERFIL_PRIVILEGE";
    public static final String VISUALIZAR_USUARIO_PRIVILEGE = "VISUALIZAR_USUARIO_PRIVILEGE";
    public static final String VISUALIZAR_GRUPO_PRIVILEGE = "VISUALIZAR_GRUPO_PRIVILEGE";
    public static final String VISUALIZAR_PLANTILLA_PRIVILEGE = "VISUALIZAR_PLANTILLA_PRIVILEGE";
    public static final String VISUALIZAR_DASHBOARD_PRIVILEGE = "VISUALIZAR_DASHBOARD_PRIVILEGE";
    public static final String VISUALIZAR_NOTIFICACION_PRIVILEGE = "VISUALIZAR_NOTIFICACION_PRIVILEGE";
    public static final String VISUALIZAR_MENU_USUARIO_PRIVILAGE = "VISUALIZAR_MENU_USUARIO_PRIVILAGE";
    public static final String VISUALIZAR_SUMARIO_PRIVILEGE = "VISUALIZAR_SUMARIO_PRIVILEGE";
    public static final String VISUALIZAR_PROCEDIMIENTOS_PRIVILEGE = "VISUALIZAR_PROVIDENCIA_PRIVILEGE";
    public static final String ADJUNTAR_ADJUNTO_PRIVILEGE = "ADJUNTAR_ADJUNTO_PRIVILEGE";
    public static final String DESCARGAR_ADJUNTO_PRIVILEGE = "DESCARGAR_ADJUNTO_PRIVILEGE";
    public static final String ASIGNAR_TIPO_A_PROVIDENCIA_PRIVILEGE = "ASIGNAR_TIPO_A_PROVIDENCIA_PRIVILEGE";
    public static final String DERIVAR_PROVIDENCIA_PRIVILEGE = "DERIVAR_PROVIDENCIA_PRIVILEGE";
    public static final String ADJUNTAR_DOCUMENTO_PRIVILEGE = "ADJUNTAR_DOCUMENTO_PRIVILEGE";
    public static final String DESCARGAR_DOCUMENTO_PRIVILEGE = "DESCARGAR_DOCUMENTO_PRIVILEGE";

//    public static final String LEER_PRIVILEGE = "LEER_PRIVILEGE";
//    public static final String ACTUALIZAR_PRIVILEGE = "ACTUALIZAR_PRIVILEGE";
//    public static final String ELIMINAR_PRIVILEGE = "ELIMINAR_PRIVILEGE";
//    public static final String VISUALIZAR_DERIVACION_PRIVILEGE = "VISUALIZAR_DERIVACION_PRIVILEGE";
//    public static final String VALIDAR_PROVIDENCIA_PRIVILEGE = "VALIDAR_PROVIDENCIA_PRIVILEGE";
//    public static final String VISAR_PROVIDENCIA_PRIVILEGE = "VISAR_PROVIDENCIA_PRIVILEGE";
//    public static final String EXPORTAR_A_EXCEL_PRIVILEGE = "EXPORTAR_A_EXCEL_PRIVILEGE";
//    public static final String ASIGNAR_NUMERO_PRIVILAGE = "ASIGNAR_NUMERO_PRIVILAGE";
//    public static final String ASIGNAR_PROVIDENCIA_A_OTROS_PRIVILEGE = "ASIGNAR_PROVIDENCIA_A_OTROS_PRIVILEGE";
//    public static final String USAR_PLANTILLA_PRIVILEGE = "USAR_PLANTILLA_PRIVILEGE";
//    public static final String DEVOLVER_PROVIDENCIA_PRIVILEGE = "DEVOLVER_PROVIDENCIA_PRIVILEGE";
//    public static final String VISUALIZAR_PRIVILEGE = "VISUALIZAR_PRIVILEGE";
//    public static final String EDITAR_SUMARIO_PRIVILEGE = "EDITAR_SUMARIO_PRIVILEGE";
//    public static final String EDITAR_FICHA_INGRESO_PRIVILEGE = "EDITAR_FICHA_INGRESO_PRIVILEGE";


    private AuthoritiesConstants() {
    }
}
