//package com.gruposolux.rcivil.pdisciplinario.domain.enumeration;
//
//public enum Estados  {
//    NUEVA_PROVIDENCIA,
//    PROVIDENCIA_SELECCION_FISCAL,
//    PROVIDENCIA_PRIMERA_PRORROGA,
//
//    PROVIDENCIA_INFORME_JURIDICO,
//    PROVIDENCIA_SOBRECEER,
//    PROVIDENCIA_ABSOLVER,
//    PROVIDENCIA_SANCION,
//    PROVIDENCIA_APELACION,
//    PROVIDENCIA_REABRE,
//    RESOLUCION_Y_MEMO,
//    FIRMA_RESOLUCION,
//    NUMERO_DGDP,
//    ELABORACION_NOTIFICACION_FISCAL,
//    NOTIFICACION_FISCAL,
//    INVESTIGACION,
//    NOTIFICACION_INCULPADO,
//    TERMINO_PROBATORIO,
//    VISTA_FISCAL,
//    INFORME_JURIDICO,
//
//}


