package com.gruposolux.rcivil.pdisciplinario.domain.enumeration;

public enum EtapaProvidencia {
    NUEVA_PROVIDENCIA,
    PROVIDENCIA_SELECCION_FISCAL,
    PROVIDENCIA_PRIMERA_PRORROGA,
    PROVIDENCIA_SEGUNDA_PRORROGA_,
    PROVIDENCIA_INFORME_JURIDICO,
    PROVIDENCIA_SOBRECEER,
    PROVIDENCIA_ABSOLVER,
    PROVIDENCIA_SANCIONAR,
    PROVIDENCIA_SANCIONAR_INCULPADO_APELA,
    PROVIDENCIA_SANCIONAR_INCULPADO_NO_APELA,
    PROVIDENCIA_REABRE

}
