package com.gruposolux.rcivil.pdisciplinario.domain.enumeration;

/**
 * The TipoDerivacion enumeration.
 */
public enum TipoDerivacion {
    VER,
    RESPONDER,
    DERIVAR,
    DEVUELVE,
    ENTREGA_ABOGADO,
    ENTREGA_FISCAL,
    NOTIFICA_FISCAL,
    ENTREGA_FUNCIONARIO,
    NOTIFICA_FUNCIONARIO,
    PROVIDENCIA_ENVIADA_SECREATARIA_SUBDIRECCION,
    PROVIDENCIA_ENVIADA_SECRETARIA_DIRECCION,
    PROVIDENCIA_ENVIADA_SUBDIRECCION,
    PROVIDENCIA_ENVIADA_A_UPD,
    PROVIDENCIA_ENVIADA_DIRECCION,
    SUMARIO_ENVIADA_A_DGDP_PARA_DAR_NUMERO,
    DERIVA_PARA_ABSOLVER,
    DERIVA_PARA_SOBRESEER,
    VALIDA_SUBDIRECCION,
    ASIGNA_PARA_REVISION,
    NOTIFICA_ABOGADO_PARA_REVISAR,
    ESPERA_ASIGNACION_ABOGADO,
    ESPERA_ASIGNACION_FISCAL,
    ESPERA_FICHA_INGRESO,
    DGDP
}
